### ISSUE TITLE
Do we need to have BIOS 1.14 to be able to run the latest EFI?

### ISSUE THREAD

**Issue by johncodeos** [kreizlie/HP-ProBook-430-G5-Hackintosh#18]
Do we need need to have BIOS 1.14 to run the EFI-0.6.7b without any problem?
I have 1.08 (from 2019), and it loads very slow(infinite) on the Apple logo screen.

Also, can you update the EFI to 0.6.8?

Thank you!

**Comment by kreizlie** [comment]
Hi friend, YES, you need BIOS 1.14


On April 14, 2021 at 3:11:36 PM, John ***@***.***) wrote:

Do we need need to have BIOS 1.14 to run the EFI-0.6.7b without any problem?
I have 1.08 (from 2019), and it loads very slow(infinite) on the Apple logo
screen.

Also, can you update the EFI to 0.6.8?

Thank you!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kreizlie/HP-ProBook-430-G5-Hackintosh/issues/18>, or
unsubscribe
